module.exports = [
    {
      id: 0,
      item_name: "Yankee Tickets",
      amount: 45.0,
      date: "07/09/2023",
      from: "StubHub",
      category: "Entertainment",
    },
    {
      id: 1,
      item_name: "Massar Capital Management",
      amount: 570.0,
      date: "07/05/2023",
      from: "Employer",
      category: "Deposit",
    },
    {
      id: 2,
      item_name: "Phone Bill",
      amount: 150.0,
      date: "07/08/2023",
      from: "at&t",
      category: "Bills",
    },
    {
      id: 3,
      item_name: "Car Insurance",
      amount: 125.0,
      date: "07/10/2023",
      from: "Geico",
      category: "Expenses",
    },
    {
      id: 4,
      item_name: "John Zelle",
      amount: 80.0,
      date: "07/07/2023",
      from: "John Apple",
      category: "Deposit",
    },
    {
      id: 5,
      item_name: "Gas bill",
      amount: 50.0,
      date: "07/06/2023",
      from: "Utility company",
      category: "Bills",
    },
  ];